export const ADD_TO_CART = "ADD_TO_CART";

export const EMPLOYEE_LIST = "EMPLOYEE_LIST";
export const SET_EMPLOYEE_LIST = "SET_EMPLOYEE_LIST";

export const REGISTER_EMPLOYEE = "REGISTER_EMPLOYEE";

export const SET_EMPLOYEE_DATA = "SET_EMPLOYEE_DATA";
export const LOGIN_EMPLOYEE = "LOGIN_EMPLOYEE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const UPDATE_EMPLOYEE_DATA = "UPDATE_EMPLOYEE_DATA";
export const SET_SINGLE_EMPLOYEE_DATA = "SET_SINGLE_EMPLOYEE_DATA";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
